---
version: "2"

run:
  tests: true

linters:
  default: all
  disable:
    # restrictive
    - exhaustruct
    - varnamelen
    - nlreturn
    - funlen
    - nonamedreturns
    - gochecknoglobals
    - wsl
    - nakedret
    - err113
    # enable later
    - wrapcheck
    - godox
    - mnd
    - unused
    - revive
    - testpackage
    - paralleltest
    - promlinter
    - lll
    - ireturn
    - gocognit
    - cyclop
    - gochecknoinits
    - forcetypeassert
    - nilerr
    - dupl
    - containedctx
  settings:
    depguard:
      rules:
        main:
          list-mode: strict
          files:
            - $all
          allow:
            - $gostd
            - golang.org/x/net
            - git.moderntv.eu
            - github.com/moderntv
            - github.com/rs/zerolog
            - github.com/gin-gonic/gin
            - gopkg.in/yaml.v2
            - github.com/spf13/viper
            - github.com/prometheus/client_golang
            - github.com/grpc-ecosystem/go-grpc-prometheus
            - github.com/rantav/go-grpc-channelz
            - github.com/rkollar/go-grpc-middleware
            - google.golang.org/grpc
            - github.com/fsnotify/fsnotify
            - github.com/cespare/xxhash
            - github.com/hashicorp/consul
            - github.com/google/uuid
            - github.com/stretchr/testify

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 120
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

issues:
  fix: true

output:
  formats:
    text:
      path: stdout
    tab:
      path: golangci-lint.out
      colors: false
    html:
      path: golangci-lint.out.html
