// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/greeter/greeter.proto

// package definition

package greeter

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// messages' definitions
type GreetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetingRequest) Reset() {
	*x = GreetingRequest{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingRequest) ProtoMessage() {}

func (x *GreetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingRequest.ProtoReflect.Descriptor instead.
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{0}
}

func (x *GreetingRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GreetingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GreetingResponse) Reset() {
	*x = GreetingResponse{}
	mi := &file_proto_greeter_greeter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GreetingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GreetingResponse) ProtoMessage() {}

func (x *GreetingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_greeter_greeter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GreetingResponse.ProtoReflect.Descriptor instead.
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return file_proto_greeter_greeter_proto_rawDescGZIP(), []int{1}
}

func (x *GreetingResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_proto_greeter_greeter_proto protoreflect.FileDescriptor

const file_proto_greeter_greeter_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/greeter/greeter.proto\x12\aexample\"%\n" +
	"\x0fGreetingRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\".\n" +
	"\x10GreetingResponse\x12\x1a\n" +
	"\bgreeting\x18\x01 \x01(\tR\bgreeting2P\n" +
	"\x0eGreeterService\x12>\n" +
	"\x05SayHi\x12\x18.example.GreetingRequest\x1a\x19.example.GreetingResponse\"\x00B:Z8github.com/moderntv/cadre/examples/proto/greeter;greeterb\x06proto3"

var (
	file_proto_greeter_greeter_proto_rawDescOnce sync.Once
	file_proto_greeter_greeter_proto_rawDescData []byte
)

func file_proto_greeter_greeter_proto_rawDescGZIP() []byte {
	file_proto_greeter_greeter_proto_rawDescOnce.Do(func() {
		file_proto_greeter_greeter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_greeter_greeter_proto_rawDesc), len(file_proto_greeter_greeter_proto_rawDesc)))
	})
	return file_proto_greeter_greeter_proto_rawDescData
}

var file_proto_greeter_greeter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_greeter_greeter_proto_goTypes = []any{
	(*GreetingRequest)(nil),  // 0: example.GreetingRequest
	(*GreetingResponse)(nil), // 1: example.GreetingResponse
}
var file_proto_greeter_greeter_proto_depIdxs = []int32{
	0, // 0: example.GreeterService.SayHi:input_type -> example.GreetingRequest
	1, // 1: example.GreeterService.SayHi:output_type -> example.GreetingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_greeter_greeter_proto_init() }
func file_proto_greeter_greeter_proto_init() {
	if File_proto_greeter_greeter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_greeter_greeter_proto_rawDesc), len(file_proto_greeter_greeter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_greeter_greeter_proto_goTypes,
		DependencyIndexes: file_proto_greeter_greeter_proto_depIdxs,
		MessageInfos:      file_proto_greeter_greeter_proto_msgTypes,
	}.Build()
	File_proto_greeter_greeter_proto = out.File
	file_proto_greeter_greeter_proto_goTypes = nil
	file_proto_greeter_greeter_proto_depIdxs = nil
}
